// Regenerates src/data/messier.ts — the 110 Messier objects as deep-sky
// destinations.
//
// Positions, types, angular sizes, and common names come from
// d3-celestial's messier.json (BSD-3-Clause, © Olaf Frohn); distances come
// from Wikidata (CC0), taking the median of all published distance claims
// per object (they vary by source — M31 alone carries a dozen).
//
// Usage: node scripts/generate-messier.mjs
// (fetches both sources live; M73 has no Wikidata distance — SEDS' 2.5 kly)

import { writeFileSync } from 'node:fs';

const LY = 9.4607e15;

const messierUrl = 'https://raw.githubusercontent.com/ofrohn/d3-celestial/master/data/messier.json';
const sparql = `SELECT ?code ?dist ?unitLabel WHERE {
  ?obj p:P528 ?st . ?st ps:P528 ?code ; pq:P972 wd:Q14530 .
  ?obj p:P2583 ?ds . ?ds psv:P2583 ?vn .
  ?vn wikibase:quantityAmount ?dist ; wikibase:quantityUnit ?unit .
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". } }`;

const cel = await (await fetch(messierUrl)).json();
const wd = await (
  await fetch(`https://query.wikidata.org/sparql?format=json&query=${encodeURIComponent(sparql)}`, {
    headers: { 'User-Agent': 'UniverseAtlas/1.0 (github.com/chrisjz/universe)' },
  })
).json();

// Normalize every distance claim to light-years, then median per object.
const UNIT_LY = {
  'light-year': 1,
  parsec: 3.26156,
  kiloparsec: 3261.56,
  megaparsec: 3261560,
};
const dists = {};
for (const r of wd.results.bindings) {
  const code = r.code.value.replace(/\s+/g, '');
  const u = UNIT_LY[r.unitLabel.value];
  if (!u) continue;
  (dists[code] ??= []).push(parseFloat(r.dist.value) * u);
}
const median = (a) => {
  const s = [...a].sort((x, y) => x - y);
  return s[Math.floor(s.length / 2)];
};

const rows = [];
for (const f of cel.features) {
  const m = f.properties.name; // "M1"
  const n = parseInt(m.slice(1), 10);
  const [ra, dec] = f.geometry.coordinates; // degrees (RA already in degrees)
  const distLy = dists[m] ? median(dists[m]) : 2500; // M73 fallback (SEDS)
  // Major axis in arcminutes ("6x4", "25", "9x7").
  const major = parseFloat(String(f.properties.dim).split(/[x×]/)[0]) || 5;
  const sizeM = 2 * distLy * LY * Math.tan(((major / 60) * Math.PI) / 180 / 2);
  rows.push({
    n,
    name: f.properties.alt || '',
    ra,
    dec,
    distLy: Number(distLy.toPrecision(4)),
    sizeM: Number(sizeM.toPrecision(4)),
    type: f.properties.type,
    mag: f.properties.mag,
  });
}
rows.sort((a, b) => a.n - b.n);

const lines = rows.map(
  (r) =>
    `  [${r.n}, ${JSON.stringify(r.name)}, ${r.ra}, ${r.dec}, ${r.distLy}, ${r.sizeM}, ${JSON.stringify(r.type)}, ${r.mag}],`,
);
writeFileSync(
  'src/data/messier.ts',
  `// Generated by scripts/generate-messier.mjs — do not edit by hand.
// The 110 Messier objects: positions/types/sizes from d3-celestial
// (BSD-3-Clause, © Olaf Frohn), distances from Wikidata (CC0, median of
// published claims). Fields: M number, common name, RA°, Dec° (J2000),
// distance (ly), physical major axis (m), type, apparent magnitude.

export type MessierObject = [number, string, number, number, number, number, string, number];

export const MESSIER: MessierObject[] = [
${lines.join('\n')}
];
`,
);
console.log(`wrote ${rows.length} objects; with Wikidata distances: ${rows.filter((r) => dists['M' + r.n]).length}`);
