// Regenerates src/data/brightstars.ts from the HYG star database
// (https://github.com/astronexus/HYG-Database, CC BY-SA 4.0).
//
//   curl -sL https://raw.githubusercontent.com/astronexus/HYG-Database/main/hyg/CURRENT/hygdata_v41.csv -o /tmp/hyg.csv
//   node scripts/generate-stars.mjs /tmp/hyg.csv
//
// Emits the N brightest stars (by apparent magnitude) with positions
// converted from HYG's equatorial cartesian parsecs into the scene's
// sun-frame meters: X toward the anti-galactic-center (the Sun sits at
// +X of the galaxy frame), Y toward the north galactic pole, Z = l≈90°.

import { readFileSync, writeFileSync } from 'node:fs';

const N = 300;
const PC = 3.0857e16; // meters

// J2000 equatorial -> galactic rotation (rows: to-center, l=90, NGP).
const M = [
  [-0.0548755604, -0.8734370902, -0.4838350155],
  [+0.4941094279, -0.44482963, +0.7469822445],
  [-0.867666149, -0.1980763734, +0.4559837762],
];

const csv = readFileSync(process.argv[2], 'utf8').split('\n');
const header = csv[0].replace(/"/g, '').split(',');
const col = Object.fromEntries(header.map((h, i) => [h, i]));

const stars = [];
for (let i = 1; i < csv.length; i++) {
  const f = csv[i].split(',');
  if (f.length < header.length) continue;
  const id = f[col.id];
  const mag = parseFloat(f[col.mag]);
  const dist = parseFloat(f[col.dist]);
  if (id === '0' || !Number.isFinite(mag) || mag > 3.6) continue;
  if (!Number.isFinite(dist) || dist <= 0 || dist >= 100000) continue; // 100000 = unknown in HYG
  const eq = [parseFloat(f[col.x]), parseFloat(f[col.y]), parseFloat(f[col.z])];
  const g = M.map((row) => row[0] * eq[0] + row[1] * eq[1] + row[2] * eq[2]);
  // scene = (-x_gal, z_gal, y_gal), right-handed, meters
  const pos = [-g[0] * PC, g[2] * PC, g[1] * PC];
  // 3D space velocity from proper motion (pmrarad/pmdecrad, rad/yr, cos-dec
  // included) + radial velocity: v_t = d * mu along the equatorial tangent.
  const ra = (parseFloat(f[col.ra]) || 0) * (Math.PI / 12); // hours -> rad
  const decl = (parseFloat(f[col.dec]) || 0) * (Math.PI / 180);
  const mua = parseFloat(f[col.pmrarad]) || 0;
  const mud = parseFloat(f[col.pmdecrad]) || 0;
  const rvKms = parseFloat(f[col.rv]) || 0;
  const east = [-Math.sin(ra), Math.cos(ra), 0];
  const north = [-Math.sin(decl) * Math.cos(ra), -Math.sin(decl) * Math.sin(ra), Math.cos(decl)];
  const radial = [Math.cos(decl) * Math.cos(ra), Math.cos(decl) * Math.sin(ra), Math.sin(decl)];
  const KMS_TO_M_YR = 3.15576e10;
  const dM = dist * PC;
  const vEq = [0, 1, 2].map((k) => dM * (mua * east[k] + mud * north[k]) + rvKms * KMS_TO_M_YR * radial[k]);
  const vG = M.map((row) => row[0] * vEq[0] + row[1] * vEq[1] + row[2] * vEq[2]);
  const vel = [-vG[0], vG[2], vG[1]];
  stars.push({
    pos,
    vel,
    mag,
    ci: parseFloat(f[col.ci]) || 0,
    lum: parseFloat(f[col.lum]) || 1,
    name: (f[col.proper] || '').replace(/"/g, ''),
  });
}

stars.sort((a, b) => a.mag - b.mag);
const top = stars.slice(0, N);

const e = (v) => Number(v.toPrecision(5));
const rows = top.map(
  (s) =>
    `  [${e(s.pos[0])}, ${e(s.pos[1])}, ${e(s.pos[2])}, ${e(s.mag)}, ${e(s.ci)}, ${e(s.lum)}, ${JSON.stringify(s.name)}, ${e(s.vel[0])}, ${e(s.vel[1])}, ${e(s.vel[2])}],`,
);

writeFileSync(
  'src/data/brightstars.ts',
  `// Generated by scripts/generate-stars.mjs — do not edit by hand.
// The ${N} brightest stars from the HYG database v4.1
// (https://github.com/astronexus/HYG-Database, CC BY-SA 4.0).
// Fields: x, y, z (meters, sun frame, galactic orientation),
// apparent magnitude, color index (B-V), luminosity (solar), proper name,
// vx, vy, vz (meters/year — the star's real 3D space velocity).

export type BrightStar = [number, number, number, number, number, number, string, number, number, number];

export const BRIGHT_STARS: BrightStar[] = [
${rows.join('\n')}
];
`,
);
console.log(`wrote ${top.length} stars; named: ${top.filter((s) => s.name).length}`);
